//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.312
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazTerceraEdad.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InterfazTerceraEdad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap browser_1 {
            get {
                object obj = ResourceManager.GetObject("browser_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browser_2 {
            get {
                object obj = ResourceManager.GetObject("browser_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {\rtf1\ansi\ansicpg1252\deff0\deflang13322{\fonttbl{\f0\fscript\fprq2\fcharset0 Comic Sans MS;}{\f1\fswiss\fcharset0 Arial;}}
        ///{\*\generator Msftedit 5.41.21.2507;}\viewkind4\uc1\pard\qc\b\f0\fs40 Comprar el 20 diciembre\b0\par
        ///\pard\par
        ///Pan\par
        ///Pavo\par
        ///Arroz\par
        ///Papas\par
        ///Carne\par
        ///\par
        ///\i Pasar a la farmacia\i0\f1\fs20\par
        ///}
        ///.
        /// </summary>
        internal static string doc_1 {
            get {
                return ResourceManager.GetString("doc_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {\rtf1\ansi\ansicpg1252\deff0\deflang13322{\fonttbl{\f0\froman\fprq2\fcharset0 Georgia;}{\f1\fswiss\fcharset0 Arial;}}
        ///{\*\generator Msftedit 5.41.21.2507;}\viewkind4\uc1\pard\b\f0\fs28 Medicina con Receta Medicinas Comunes usadas para Tratar la Enfermedad Card\&apos;edaca \par
        ///\b0\par
        ///\i Aspirina\i0\par
        /// Ayuda a prevenir ataques al coraz\&apos;f3n y coagulaci\&apos;f3n de la sangre; discuta la dosis apropiada con su doctor para evitar \&apos;falceras estomacales.\par
        /// \par
        ///\i Inhibidores de la ECA\i0\par
        /// Detienen la p [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string doc_2 {
            get {
                return ResourceManager.GetString("doc_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {\rtf1\ansi\ansicpg1252\deff0\deflang13322{\fonttbl{\f0\froman\fprq2\fcharset0 Times New Roman;}{\f1\froman\fprq2\fcharset0 Georgia;}{\f2\fswiss\fcharset0 Arial;}}
        ///{\*\generator Msftedit 5.41.21.2507;}\viewkind4\uc1\pard\b\f0\fs36 Otro ejemplo\par
        ///\par
        ///Medicina con Receta Medicinas Comunes usadas para Tratar la Enfermedad Card\&apos;edaca \par
        ///\b0\par
        ///\i Aspirina\i0\par
        /// Ayuda a prevenir ataques al coraz\&apos;f3n y coagulaci\&apos;f3n de la sangre; discuta la dosis apropiada con su doctor para evitar \&apos;falceras est [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string doc_3 {
            get {
                return ResourceManager.GetString("doc_3", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap edit_1 {
            get {
                object obj = ResourceManager.GetObject("edit_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_2 {
            get {
                object obj = ResourceManager.GetObject("edit_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream high_freq {
            get {
                return ResourceManager.GetStream("high_freq", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap mail_1 {
            get {
                object obj = ResourceManager.GetObject("mail_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_2 {
            get {
                object obj = ResourceManager.GetObject("mail_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap money_1 {
            get {
                object obj = ResourceManager.GetObject("money_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap money_2 {
            get {
                object obj = ResourceManager.GetObject("money_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nuke_1 {
            get {
                object obj = ResourceManager.GetObject("nuke_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nuke_2 {
            get {
                object obj = ResourceManager.GetObject("nuke_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap off_1 {
            get {
                object obj = ResourceManager.GetObject("off_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap off_2 {
            get {
                object obj = ResourceManager.GetObject("off_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
