//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.1434
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemperatureLogger.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TemperatureLogger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrollado por Erwin Ried
        ///Versión 0.1
        ///
        ///Esta aplicación utiliza ZedGraph Class Library
        ///http://zedgraph.sourceforge.net.
        /// </summary>
        internal static string AppAboutText {
            get {
                return ResourceManager.GetString("AppAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca de.
        /// </summary>
        internal static string AppAboutTitle {
            get {
                return ResourceManager.GetString("AppAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}	{1}.
        /// </summary>
        internal static string AppExportColumnsFormat {
            get {
                return ResourceManager.GetString("AppExportColumnsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timestamp	Temperature.
        /// </summary>
        internal static string AppExportColumnsHeader {
            get {
                return ResourceManager.GetString("AppExportColumnsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al exportar los datos.
        /// </summary>
        internal static string AppExportErrorText {
            get {
                return ResourceManager.GetString("AppExportErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string AppExportErrorTitle {
            get {
                return ResourceManager.GetString("AppExportErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos tabulados, columnas con encabezado (*.txt)|*.txt|Datos tabulados (*.txt)|*.txt.
        /// </summary>
        internal static string AppExportFilter {
            get {
                return ResourceManager.GetString("AppExportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar datos capturados.
        /// </summary>
        internal static string AppExportTitle {
            get {
                return ResourceManager.GetString("AppExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de temperaturas (conectado al puerto {0}).
        /// </summary>
        internal static string AppTitleConnected {
            get {
                return ResourceManager.GetString("AppTitleConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de temperaturas (sin conexión).
        /// </summary>
        internal static string AppTitleDisconnected {
            get {
                return ResourceManager.GetString("AppTitleDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temperatura (grados celsius).
        /// </summary>
        internal static string GraphLabelCelsius {
            get {
                return ResourceManager.GetString("GraphLabelCelsius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo.
        /// </summary>
        internal static string GraphLabelDatetime {
            get {
                return ResourceManager.GetString("GraphLabelDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ºC.
        /// </summary>
        internal static string GraphLabelTemperature {
            get {
                return ResourceManager.GetString("GraphLabelTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a G.
        /// </summary>
        internal static string GraphScaleFormat {
            get {
                return ResourceManager.GetString("GraphScaleFormat", resourceCulture);
            }
        }
    }
}
