//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.312
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicTacToe.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TicTacToe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Developed by Erwin Ried, designed for Mono..
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        internal static string About_title {
            get {
                return ResourceManager.GetString("About_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For this solution, the utility has been already calculated..
        /// </summary>
        internal static string Already_calculated {
            get {
                return ResourceManager.GetString("Already_calculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calculating utility, please wait....
        /// </summary>
        internal static string Calculating {
            get {
                return ResourceManager.GetString("Calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click on the board to begin, or press computer start..
        /// </summary>
        internal static string Click_to_begin {
            get {
                return ResourceManager.GetString("Click_to_begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game ended with a draw, click reset.
        /// </summary>
        internal static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Collected {0} megabytes of garbage..
        /// </summary>
        internal static string Garbage_collected {
            get {
                return ResourceManager.GetString("Garbage_collected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Garbage collector.
        /// </summary>
        internal static string Garbage_collected_title {
            get {
                return ResourceManager.GetString("Garbage_collected_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I won, sorry. To play again click reset.
        /// </summary>
        internal static string Lose {
            get {
                return ResourceManager.GetString("Lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N/A.
        /// </summary>
        internal static string Not_available {
            get {
                return ResourceManager.GetString("Not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a X.
        /// </summary>
        internal static string Player_1 {
            get {
                return ResourceManager.GetString("Player_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a O.
        /// </summary>
        internal static string Player_2 {
            get {
                return ResourceManager.GetString("Player_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solution tree successfully generated..
        /// </summary>
        internal static string Solution_generated {
            get {
                return ResourceManager.GetString("Solution_generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solution tree needs to be generated. Solving, please wait....
        /// </summary>
        internal static string Solution_tree_generation {
            get {
                return ResourceManager.GetString("Solution_tree_generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tic-Tac-Toe is already solved..
        /// </summary>
        internal static string Solved {
            get {
                return ResourceManager.GetString("Solved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tic-Tac-Toe solver.
        /// </summary>
        internal static string Solver {
            get {
                return ResourceManager.GetString("Solver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solving, please wait....
        /// </summary>
        internal static string Solving {
            get {
                return ResourceManager.GetString("Solving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thinking....
        /// </summary>
        internal static string Thinking {
            get {
                return ResourceManager.GetString("Thinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It&apos;s your turn..
        /// </summary>
        internal static string Turn {
            get {
                return ResourceManager.GetString("Turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must solve the game first..
        /// </summary>
        internal static string Unsolved {
            get {
                return ResourceManager.GetString("Unsolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Utility successfully calculated..
        /// </summary>
        internal static string Utility_calculated {
            get {
                return ResourceManager.GetString("Utility_calculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You won, to play again click reset.
        /// </summary>
        internal static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
    }
}
