//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.1434
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureConsoleLauncher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36-27-90-9A-29-C3-13-81-A0-71-EC-27-F7-C9-CA-97-72-61-82-AE-D2-9A-7D-DD-2E-54-35-" +
            "33-22-CF-B3-0A-BB-9E-3A-6D-F2-AC-2C-20-FE-23-43-63-11-D6-78-56-4D-0C-8D-30-59-30" +
            "-57-5F-60-E2-D3-D0-48-18-4D-79")]
        public string PassHash {
            get {
                return ((string)(this["PassHash"]));
            }
            set {
                this["PassHash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_utilman.exe")]
        public string RunNormally {
            get {
                return ((string)(this["RunNormally"]));
            }
            set {
                this["RunNormally"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("taskmgr.exe")]
        public string RunWhenSecure {
            get {
                return ((string)(this["RunWhenSecure"]));
            }
            set {
                this["RunWhenSecure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SYSTEM")]
        public string SystemAccount {
            get {
                return ((string)(this["SystemAccount"]));
            }
            set {
                this["SystemAccount"] = value;
            }
        }
    }
}
